import { spawnSync } from 'node:child_process';
import fs from 'node:fs';
import path from 'node:path';

const ROOT = process.cwd();
const outDir = path.join(ROOT, 'reports');
fs.mkdirSync(outDir, { recursive: true });
const reportPath = path.join(outDir, 'npm-audit-report.json');
const mdPath = path.join(ROOT, 'docs/security/NPM_AUDIT_STATUS.md');

const result = spawnSync(process.platform === 'win32' ? 'npm.cmd' : 'npm', ['audit', '--json'], {
  cwd: ROOT,
  encoding: 'utf8'
});

let payload = {};
try {
  payload = JSON.parse(result.stdout || '{}');
} catch (error) {
  payload = { parseError: error.message, raw: result.stdout || result.stderr };
}

fs.writeFileSync(reportPath, JSON.stringify(payload, null, 2));

const vulnerabilities = payload.metadata?.vulnerabilities || {};
const total = vulnerabilities.total ?? 0;
const lines = [
  '# NPM Audit Status',
  '',
  `Generated by: \`npm run security:audit\``,
  '',
  '## Summary',
  '',
  `- Total vulnerabilities: ${total}`,
  `- Critical: ${vulnerabilities.critical ?? 0}`,
  `- High: ${vulnerabilities.high ?? 0}`,
  `- Moderate: ${vulnerabilities.moderate ?? 0}`,
  `- Low: ${vulnerabilities.low ?? 0}`,
  '',
  '## Decision',
  '',
  'This report is intentionally non-destructive. Do not run `npm audit fix --force` automatically on this project because major upgrades can break Firebase/admin integrations.',
  '',
  '## Safe remediation flow',
  '',
  '```bash',
  'npm audit',
  'npm outdated',
  'npm install <package>@latest',
  'npm run final:ultimate',
  '```',
  '',
  'If Firebase or Firebase Admin packages require a major upgrade, validate authentication, Firestore reads/writes, storage, admin-only actions, and deployment before merging.',
  '',
  `Raw JSON report: \`reports/npm-audit-report.json\``,
  ''
];
fs.writeFileSync(mdPath, lines.join('\n'));
console.log(`✅ Wrote ${path.relative(ROOT, mdPath)} and ${path.relative(ROOT, reportPath)}.`);
