import { useEffect, useMemo, useState } from 'react';
import { addDoc, collection, onSnapshot, query, serverTimestamp, where } from 'firebase/firestore';
import { db } from '@services/firebase';
import nahhasLogo from '@assets/nahhas-logo-transparent.png';
import './smart-teacher.css';
const shuffle=(a)=>[...a].sort(()=>Math.random()-.5);
export default function StudentSmartTeacherPopup({user,userData}){
 const [open,setOpen]=useState(false),[groups,setGroups]=useState([]),[questions,setQuestions]=useState([]),[active,setActive]=useState(null),[index,setIndex]=useState(0),[choice,setChoice]=useState(null),[wrong,setWrong]=useState(0),[score,setScore]=useState(0);
 useEffect(()=>{if(!userData?.grade)return;return onSnapshot(query(collection(db,'smart_teacher_groups'),where('grades','array-contains',userData.grade)),s=>setGroups(s.docs.map(d=>({id:d.id,...d.data()})).filter(g=>g.status!=='disabled')),()=>setGroups([]));},[userData?.grade]);
 const start=(g)=>{setActive(g);setIndex(0);setChoice(null);setWrong(0);setScore(0);onSnapshot(query(collection(db,'question_bank'),where('smartTeacherGroupId','==',g.id)),s=>setQuestions(shuffle(s.docs.map(d=>({id:d.id,...d.data()}))).slice(0,g.questionsPerSession||10)),()=>setQuestions([]));};
 const q=questions[index]; const correct=choice!==null&&choice===q?.correctIdx;
 const submit=async(i)=>{setChoice(i);if(i===q.correctIdx){setScore(v=>v+1);await addDoc(collection(db,'smart_teacher_attempts'),{studentId:user.uid,groupId:active.id,questionId:q.id,correct:true,createdAt:serverTimestamp()});}else{setWrong(v=>v+1);await addDoc(collection(db,'smart_teacher_attempts'),{studentId:user.uid,groupId:active.id,questionId:q.id,correct:false,createdAt:serverTimestamp()});}};
 const next=()=>{if(index+1>=questions.length){setActive({...active,finished:true});return;}setIndex(v=>v+1);setChoice(null);setWrong(0);};
 return <><button className="st-fab" onClick={()=>setOpen(true)}><span>ن✦</span><b>المعلم الذكي</b></button>{open&&<div className="st-modal-backdrop" onClick={()=>setOpen(false)}><section className="st-modal" onClick={e=>e.stopPropagation()} dir="rtl"><button className="st-close" onClick={()=>setOpen(false)}>×</button><header><img src={nahhasLogo} alt=""/><div><small>تدريب يتطور مع مستواك</small><h2>المعلم الذكي</h2><p>أهلًا يا {userData?.name||'بطل'}، جاهز نراجع معًا؟</p></div></header>{!active?<div className="st-student-groups">{groups.map(g=><button key={g.id} onClick={()=>start(g)}><b>{g.title}</b><span>{g.branch} • {g.lesson}</span><small>{g.questionCount||0} سؤال متاح</small></button>)}{!groups.length&&<p>لا توجد تدريبات منشورة لصفك الآن.</p>}</div>:active.finished?<div className="st-finish"><h3>أحسنت 👏</h3><p>أنهيت التدريب بنتيجة {score} من {questions.length}</p><button onClick={()=>setActive(null)}>اختيار تدريب آخر</button></div>:q?<div className="st-question"><div className="st-progress"><span>السؤال {index+1} من {questions.length}</span><b>{active.lesson}</b></div><h3>{q.text}</h3><div className="st-options">{(q.options||[]).map((op,i)=><button disabled={choice!==null} className={choice!==null?(i===q.correctIdx?'correct':i===choice?'wrong':''):''} onClick={()=>submit(i)} key={i}>{op}</button>)}</div>{choice!==null&&!correct&&<div className="st-coach"><b>لسه هنحاول تاني</b>{wrong>=1&&active.hint&&<p>💡 {active.hint}</p>}{wrong>=2&&active.rule&&<p>📘 {active.rule}</p>}{wrong>=2&&active.example&&<p>مثال: {active.example}</p>}</div>}{choice!==null&&correct&&<button className="st-next" onClick={next}>إجابة صحيحة — التالي</button>}{choice!==null&&!correct&&<button className="st-next" onClick={()=>{setChoice(null);setIndex((index+1)%questions.length)}}>سؤال آخر من نفس الدرس</button>}</div>:<p>جاري تجهيز الأسئلة...</p>}</section></div>}</>;
}
