export const COLLECTIONS = Object.freeze({
  USERS: 'users',
  CONTENT: 'content',
  MESSAGES: 'messages',
  EXAMS: 'exams',
  EXAM_RESULTS: 'exam_results',
  ANNOUNCEMENTS: 'announcements',
  QUOTES: 'quotes',
  SMART_HOMEWORKS: 'smart_homeworks',
  HOMEWORK_RESULTS: 'homework_results',
  SUBSCRIPTION_CODES: 'subscription_codes',
  ASSIGNMENTS: 'assignments',
  ASSIGNMENT_SUBMISSIONS: 'assignment_submissions',
  STUDENT_MISTAKES: 'student_mistakes',
  VIDEO_VIEWS: 'video_views',
  NOTIFICATIONS: 'notifications',
  PASSWORD_RESET_REQUESTS: 'password_reset_requests',
  EXAM_ACCESS_OVERRIDES: 'exam_access_overrides',
});
